# Generated by Django 3.1.4 on 2021-01-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pop',
            name='text_pop',
            field=models.CharField(max_length=1500),
        ),
    ]
