# Generated by Django 3.1.4 on 2021-01-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folium_map0', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLight',
            fields=[
                ('id_img', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25)),
                ('img_file', models.FileField(default='', upload_to='')),
                ('source', models.CharField(max_length=100)),
            ],
        ),
    ]
